routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();


Route::match(["GET", "POST"], "/register", function(){
 return redirect("/login");
})->name("register");

Route::get('/user/profile', 'UserController@index');

// Generating view
    Route::get('/tours', 'ViewController@tourview')->name('tours');
    Route::get('/tours/detail/{id}', 'ViewController@tourdetail')->name('tours.detail');

    Route::get('/', 'ViewController@index');

    Route::get('/bus', 'ViewController@busview')->name('bus');
    Route::get('/bus/details/{id}', 'ViewController@busdetail')->name('bus.detail');
    
    Route::get('/contact', 'ViewController@contactview')->name('contact');
    Route::post('/contact', 'ViewController@store')->name('contact.post');


Route::group(['middleware' => 'auth'], function(){
   
    // Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('vacations', 'VacationController');
    Route::resource('buses', 'BusController');
    Route::resource('tasks', 'TasksController'); //creating timeline

    // creating bus
    Route::get('/home', 'EventsController@schedule')->name('events.schedule');
    Route::get('/ajax/bus/search','EventsController@ajaxSearchbus'); 
    Route::get('/ajax/vacation/search','EventsController@ajaxSearchvacation');
    Route::get('/events', 'EventsController@index')->name('events');
    Route::get('events/create', 'EventsController@create')->name('events.create');
    Route::post('events/create', 'EventsController@addEvent')->name('events.add');

    // setting timer
    Route::get('timer', 'TimerController@index')->name('timer');
    Route::put('timer/update', 'TimerController@update')->name('timers');
    Route::get('timer/running', 'TimerController@mytime')->name('timer.mytime');

    // profile and setting
    Route::get('profile', 'UserController@index')->name('user.profile');
    Route::get('setting', 'UserController@seting')->name('user.setting');
});

app/Vacation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Vacation extends Model
{
    public function events(){
        return $this->belongsToMany("App\Events");
    }
}

app/Http/Controllers/VacationController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class VacationController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $vacation = \App\Vacation::paginate(10);
        $filter =  $request->get('destination');

        if($filter){
            $vacation = \App\Vacation::where("destination", "LIKE","%$filter%")->paginate(10);
        }
        return view('vacations.index', ['vacations' => $vacation]);
    }


    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('vacations.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $destination = $request->get('destination');
        $new_vacation = new \App\Vacation;

        $new_vacation->destination = $destination;
        $new_vacation->location = $request->get('location');
        $new_vacation->facilities = $request->get('facilities');
        $new_vacation->timeline = $request->get('timeline');
        $new_vacation->status = $request->get('status');
        $new_vacation->terms = $request->get("terms");
        $new_vacation->slug = str_slug($destination, '-');

        if($request->file('image')){
            $file = $request->file('image')->store('images-destination', 'public');
            $new_vacation->image = $file;
        } 

        $pathImages = [];

        if(count($request->file('image_desc'))) {
            foreach($request->file('image_desc') as $img) {
                $file = $img->store('images-destination', 'public');
                array_push($pathImages, $file);
            }
        }

        $new_vacation->image_description = json_encode($pathImages);
        $new_vacation->save();
        return redirect()->route('vacations.index')->with('status', 'trip successfully created');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $vacation = \App\Vacation::findOrFail($id);
        return view('vacations.show', ['vacations' => $vacation]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $edit = \App\Vacation::findOrFail($id);
        return view('vacations.edit',['vacation' => $edit]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $vacation = \App\Vacation::findOrFail($id);
        $destination =  $request->get('destination');
        $vacation->destination = $destination;
        $vacation->location = $request->get('location');
        $vacation->facilities = $request->get('facilities');
        $vacation->timeline = $request->get('timeline');
        $vacation->status = $request->get('status');
        $vacation->terms = $request->get("terms");
        $vacation->slug = str_slug($destination, '-');

        if($request->file('image')){
            if($vacation->image && file_exists(storage_path('app/public/' . $category->image))){
                \Storage::delete('public/' . $vacation->destination);
            }

            $new_image = $request->file('image')->store('images-destination', 'public');
            $vacation->image = $new_image;
        }

        $vacation->save();
        
        return redirect()->route('vacations.index', ['id' => $id])->with('status', 'vacation successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $vacation = \App\Vacation::findOrFail($id);
        $vacation->delete();
        return redirect()->route('vacations.index')->with('status', 'Category successfully moved to trash');

    }
}

resources/views/vacations/create.blade.php
@extends('layouts.global')

@section('title')
    Create Trip
@endsection

@section('content')
    <form enctype="multipart/form-data" class="bg-white shadow-sm p-3"  action="{{route('vacations.store')}}" method="POST">
        @csrf

        @if(session('status'))
            <div class="alert alert-success">
                {{session('status')}}
            </div>
        @endif 

        <label>Destination</label><br>
        <input type="text" class="form-control" name="destination">
        <br>

        <label>Location</label><br>
        <textarea  name="location" id="location" class="form-control"></textarea>

        <br>

        <label>image</label>
        <br>
        <input type="file" class="form-control" name="image">
        <br>

    <label><b>Image Description</b></label>
        <br>
        <input type="file" multiple class="form-control" name="image_desc[]">
        <br>


        <label>Status</label>
        <select name="status" class="form-control">
            <option value="AVAILABLE">Tersedia</option>
            <option value="EXPIRED">Tidak Ada</option>
        </select>
        <br>

        <label>Facilities</label><br>
        <textarea class="ckeditor"  name="facilities" class="form-control"></textarea>
        <br>

        <label>Timeline</label><br>
        <textarea class="ckeditor"  name="timeline" class="form-control"></textarea>
        <br>

        <label>Term and Condition</label><br>
        <textarea class="ckeditor" name="terms" class="form-control"></textarea>
        <br>

        <input class="btn btn-primary" type="submit" value="Save"/>

    </form>
@endsection 

resources/views/vacations/edit.blade.php
@extends('layouts.global')
@section('title')
    Edit Vacation
@endsection

@section('content')
    <form
        action="{{route('vacations.update', ['id' => $vacation->id])}}"
        enctype="multipart/form-data"
        method="POST"
        class="bg-white shadow-sm p-3">

        @csrf
        <input type="hidden" value="PUT" name="_method">

        <label>Destination</label><br>
        <input type="text" class="form-control" name="destination" value="{{$vacation->destination}}">
        <br>

        <label for="">Slug Destination</label>
        <input type="text" class="form-control" name="slug" value="{{$vacation->slug}}">
        <br>

        <label>Location</label><br>
        <input type="text" name="location" id="location" class="form-control" value="{{$vacation->location}}">

        <br>


        @if($vacation->image)
            <span>Current image</span><br>
            <img src="{{asset('storage/'. $vacation->image)}}" width="120px">
            <br><br>
        @endif

        <input
            type="file"
            class="form-control"
            name="image">
            <small class="text-muted">Let it if you wont change</small>
        <br><br>


        @if($vacation->status)
            <label>Status</label>
            
            <select name="status" class="form-control">
                <option>{{$vacation->status}}</option>
                <option value="AVAILABLE">Tersedia</option>
                <option value="EXPIRED">Tidak Ada</option>
            </select>
        @endif
        
        <br>

        <label>Facilities</label><br>
        <textarea class="ckeditor"    name="facilities" class="form-control">{{$vacation->facilities}}</textarea>
        <br>

        <label>Timeline</label><br>
        <textarea class="ckeditor"  name="timeline" class="form-control">{{$vacation->timeline}}</textarea>
        <br>

        <label>Term and Condition</label><br>
        <textarea class="ckeditor" name="terms" class="form-control">{{$vacation->terms}}</textarea>
        <br>

        <input class="btn btn-primary" type="submit" value="Save"/>
    </form>

@endsection

resources/views/vacations/index.blade.php
@extends('layouts.global')
@section('title')
    List Vacation
@endsection

@section('content')
    @if(session('status'))
        <div class="alert alert-success">
            {{session('status')}}
        </div>
    @endif 


    <div class="row">
        <div class="col-md-8">
            <form action="{{route('vacations.index')}}">
                <div class="input-group">
                    <input type="text" name="destination" class="form-control" placeholder="Filter by category name" >
                    <div class="input-group-append">
                        <input type="submit" value="Filter" class="btn btn-primary">
                    </div>
                </div>
            </form>
        </div>

        <div class="col-md-4 text-right">
            <a href="{{route('vacations.create')}}" class="btn btn-primary">Create Vacation</a>
        </div>
    </div>

    <hr class="my-3">


    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered table-stripped text-center">
                <thead>
                    <tr class="table-active text-center">
                        <th><b>Name</b></th>
                        <th><b>Slug</b></th>
                        <th><b>Location</b></th>
                        <th><b>Actions</b></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($vacations as $category)
                        <tr>
                            <td>{{$category->destination}}</td>
                            <td>{{$category->slug}}</td>
                            <td>
                                {{$category->location}}
                            </td>
                            <td >
                                <button type="submit" class="btn btn-success"  value="">
                                    <a href="{{route('vacations.edit', ['id' => $category->id])}}"><i class="fas fa-edit"></i></a>
                                </button>
                                

                                {{-- <a href="#" style="width: 50px;"><i class="far fa-trash-alt"></i></a> --}}
                                
                                <form onsubmit="return confirm('Delete this user permanently?')" class="d-inline" action="{{route('vacations.destroy', ['id' => $category->id ])}}" method="POST">
                                        @csrf
                                        <input type="hidden" name="_method" value="DELETE">

                                        <button type="submit" value="Delete" class="btn btn-danger" >
                                            <i class="far fa-trash-alt"></i> 
                                        </button>
                                        
                                        {{-- <input type="submit" value="Delete" class="btn btn-primary"> --}}
                                </form>

                                
                                
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <td colSpan="10">
                            {{$vacations->appends(Request::all())->links()}}
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>

@endsection

resources/views/vacations/show.blade.php
@extends('layouts.global')

@section('title')
    Show Delete
@endsection

@section('content')
    
@endsection