routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();


Route::match(["GET", "POST"], "/register", function(){
 return redirect("/login");
})->name("register");

Route::get('/user/profile', 'UserController@index');

// Generating view
    Route::get('/tours', 'ViewController@tourview')->name('tours');
    Route::get('/tours/detail/{id}', 'ViewController@tourdetail')->name('tours.detail');

    Route::get('/', 'ViewController@index');

    Route::get('/bus', 'ViewController@busview')->name('bus');
    Route::get('/bus/details/{id}', 'ViewController@busdetail')->name('bus.detail');
    
    Route::get('/contact', 'ViewController@contactview')->name('contact');
    Route::post('/contact', 'ViewController@store')->name('contact.post');


Route::group(['middleware' => 'auth'], function(){
   
    // Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('vacations', 'VacationController');
    Route::resource('buses', 'BusController');
    Route::resource('tasks', 'TasksController'); //creating timeline

    // creating bus
    Route::get('/home', 'EventsController@schedule')->name('events.schedule');
    Route::get('/ajax/bus/search','EventsController@ajaxSearchbus'); 
    Route::get('/ajax/vacation/search','EventsController@ajaxSearchvacation');
    Route::get('/events', 'EventsController@index')->name('events');
    Route::get('events/create', 'EventsController@create')->name('events.create');
    Route::post('events/create', 'EventsController@addEvent')->name('events.add');

    // setting timer
    Route::get('timer', 'TimerController@index')->name('timer');
    Route::put('timer/update', 'TimerController@update')->name('timers');
    Route::get('timer/running', 'TimerController@mytime')->name('timer.mytime');

    // profile and setting
    Route::get('profile', 'UserController@index')->name('user.profile');
    Route::get('setting', 'UserController@seting')->name('user.setting');
});

resources/views/buses/create.blade.php
@extends('layouts.global')
@section('title')
    Adding Bus
@endsection

@section('content')
    <form enctype="multipart/form-data" action="{{route('buses.store')}}" class="bg-white shadow-sm p-3"  method="POST">
            @csrf

            @if(session('status'))
                <div class="alert alert-success">
                    {{session('status')}}
                </div>
            @endif 
            
            <label>Bus Name</label><br>
            <input type="text" class="form-control" name="name">
            <br>
            
            <label>Description</label><br>
            <textarea class="ckeditor"  name="description" class="form-control"></textarea>
            <br>

            <label>Price</label><br>
            <input type="number" class="form-control" name="price">
            <br>

            <label>Bus Category</label>
            <select name="category" class="form-control">
                <option value="HIACE">HIAce</option>
                <option value="ELF">ELF</option>
            </select>
            <br>

            <label>image</label>
            <br>
            <input type="file" multiple class="form-control" name="image[]">
            <br>

            <label>Capacity </label>
            <br>
            <input type="number" class="form-control" name="capacity">
            <br>

            <label>Facilities</label><br>
            <textarea class="ckeditor"  name="facilities" class="form-control"></textarea>
            <br>

            <input class="btn btn-primary" type="submit" value="Save"/>

        </form>
@endsection

resources/views/buses/edit.blade.php
@extends('layouts.global')
@section('title')
    Edit Bus
@endsection

@section('content')
    <form action="{{route('buses.update', ['id' => $bus->id])}}"  enctype="multipart/form-data" method="POST" class="bg-white shadow-sm p-3">
        @csrf
        <input type="hidden" value="PUT" name="_method">

        <label>Bus name</label><br>
        <input type="text" class="form-control" name="name" value="{{$bus->name}}">
        <br>

        <label>Bus Category</label>
        <select name="category" class="form-control">
            {{-- <option selected disabled value="{{$bus->category}}">{{$bus->category}}</option> --}}
            <option value="HIACE">HIAce</option>
            <option value="ELF">ELF</option>
        </select>
        <br>

        @if($bus->image)
            <span>Current image</span><br>
            <img src="{{asset('storage/'. $bus->image)}}" width="120px">
            <br><br>
        @endif

        <input
            type="file"
            class="form-control"
            name="image">
            <small class="text-muted">Let it if you wont change</small>
        <br><br>


        <label for="">Facilities</label>
        <br>
        <textarea name="facilities"  class="ckeditor" class="form-controll">{{$bus->facilities}}</textarea>
        <br>
        <input type="submit" value="Update" class="btn btn-primary">
    
    </form>
@endsection

resources/views/buses/index.blade.php
@extends('layouts.global')
@section('title')
    List Buses
@endsection

@section('content')
    @if(session('status'))
        <div class="alert alert-success">
            {{session('status')}}
        </div>
    @endif 

    <div class="row">
        <div class="col-md-8">
            <form action="{{route('buses.index')}}">
                <div class="input-group">
                    <input type="text" name="name" class="form-control" placeholder="Filter by category name" >
                    <div class="input-group-append">
                        <input type="submit" value="Filter" class="btn btn-primary">
                    </div>
                </div>
            </form>
        </div>

        <div class="col-md-4 text-right">
            <a href="{{route('buses.create')}}" class="btn btn-primary">Add Bus</a>
        </div>
    </div>

    <hr class="my-3">


    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Capacity</th>
                <th scope="col">category</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($buses as $bus)
                <tr>
                    <th scope="row">{{$bus->id}}</th>
                    <td>{{$bus->name}}</td>
                    <td>{{$bus->capacity}}</td>
                    <td>{{$bus->category}}</td>
                    <td>
                        <button type="submit" class="btn btn-success"  value="">
                            <a href="{{route('buses.edit', ['id' => $bus->id])}}"><i class="fas fa-edit"></i></a>
                        </button>

                        <form onsubmit="return confirm('Delete this user permanently?')" class="d-inline" action="{{route('buses.destroy', ['id' => $bus->id ])}}" method="POST">
                                @csrf
                                <input type="hidden" name="_method" value="DELETE">

                                <button type="submit" value="Delete" class="btn btn-danger" >
                                    <i class="far fa-trash-alt"></i> 
                                </button>
                                
                        </form>

                    
                    </td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colSpan="10">
                {{$buses->appends(Request::all())->links()}}
                </td>
            </tr>
        </tfoot>
    </table>
@endsection