routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();


Route::match(["GET", "POST"], "/register", function(){
 return redirect("/login");
})->name("register");

Route::get('/user/profile', 'UserController@index');

// Generating view
    Route::get('/tours', 'ViewController@tourview')->name('tours');
    Route::get('/tours/detail/{id}', 'ViewController@tourdetail')->name('tours.detail');

    Route::get('/', 'ViewController@index');

    Route::get('/bus', 'ViewController@busview')->name('bus');
    Route::get('/bus/details/{id}', 'ViewController@busdetail')->name('bus.detail');
    
    Route::get('/contact', 'ViewController@contactview')->name('contact');
    Route::post('/contact', 'ViewController@store')->name('contact.post');


Route::group(['middleware' => 'auth'], function(){
   
    // Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('vacations', 'VacationController');
    Route::resource('buses', 'BusController');
    Route::resource('tasks', 'TasksController'); //creating timeline

    // creating bus
    Route::get('/home', 'EventsController@schedule')->name('events.schedule');
    Route::get('/ajax/bus/search','EventsController@ajaxSearchbus'); 
    Route::get('/ajax/vacation/search','EventsController@ajaxSearchvacation');
    Route::get('/events', 'EventsController@index')->name('events');
    Route::get('events/create', 'EventsController@create')->name('events.create');
    Route::post('events/create', 'EventsController@addEvent')->name('events.add');

    // setting timer
    Route::get('timer', 'TimerController@index')->name('timer');
    Route::put('timer/update', 'TimerController@update')->name('timers');
    Route::get('timer/running', 'TimerController@mytime')->name('timer.mytime');

    // profile and setting
    Route::get('profile', 'UserController@index')->name('user.profile');
    Route::get('setting', 'UserController@seting')->name('user.setting');
});

app/Task.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    protected $fillable = ['name', 'description', 'task_date'];
}

app/Http/Controllers/TasksController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TasksController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $tasks = Task::all();
        return view('tasks.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Task::create($request->all());
        return redirect()->route('tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/tasks/create.blade.php
@extends('layouts.global')
@section('title')
    create activity
@endsection

resources/views/tasks/index.blade.php
@extends('layouts.global')
@section('title')
    Timeline
@endsection

@section('content')

    <form enctype="multipart/form-data" class="bg-white shadow-sm p-3" action="{{ route('tasks.store') }}" method="post">
       @csrf
        <label for="">Task</label>
        <br />
        <input type="text" name="name" class="form-control" class="form-control" />
        <br />
        <label for="">Description</label>
        <br />
        <textarea name="description" class="form-control"></textarea>
        <br />
        <label for="">Start Time</label><br>
        <input type="text" name="task_date" class="date" />
        <br /><br />
        <input class="btn btn-primary" type="submit" value="Save"/>
    </form>
@endsection

@section('footer-scripts')
    <script>
    $('.date').datepicker({
        autoclose: true,
        dateFormat: "yy-mm-dd"
    });
</script>

@endsection