routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Auth::routes();


Route::match(["GET", "POST"], "/register", function(){
 return redirect("/login");
})->name("register");

Route::get('/user/profile', 'UserController@index');

// Generating view
    Route::get('/tours', 'ViewController@tourview')->name('tours');
    Route::get('/tours/detail/{id}', 'ViewController@tourdetail')->name('tours.detail');

    Route::get('/', 'ViewController@index');

    Route::get('/bus', 'ViewController@busview')->name('bus');
    Route::get('/bus/details/{id}', 'ViewController@busdetail')->name('bus.detail');
    
    Route::get('/contact', 'ViewController@contactview')->name('contact');
    Route::post('/contact', 'ViewController@store')->name('contact.post');


Route::group(['middleware' => 'auth'], function(){
   
    // Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('vacations', 'VacationController');
    Route::resource('buses', 'BusController');
    Route::resource('tasks', 'TasksController'); //creating timeline

    // creating bus
    Route::get('/home', 'EventsController@schedule')->name('events.schedule');
    Route::get('/ajax/bus/search','EventsController@ajaxSearchbus'); 
    Route::get('/ajax/vacation/search','EventsController@ajaxSearchvacation');
    Route::get('/events', 'EventsController@index')->name('events');
    Route::get('events/create', 'EventsController@create')->name('events.create');
    Route::post('events/create', 'EventsController@addEvent')->name('events.add');

    // setting timer
    Route::get('timer', 'TimerController@index')->name('timer');
    Route::put('timer/update', 'TimerController@update')->name('timers');
    Route::get('timer/running', 'TimerController@mytime')->name('timer.mytime');

    // profile and setting
    Route::get('profile', 'UserController@index')->name('user.profile');
    Route::get('setting', 'UserController@seting')->name('user.setting');
});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<!--[if IE 9]> <html class="ie9 no-js" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Admin Area @yield("title")</title>
  <link rel="stylesheet" href="{{asset('polished/polished.min.css')}}">
  <link rel="stylesheet" href="{{asset('polished/iconic/css/open-iconic-bootstrap.min.css')}}">

  <style>
    .grid-highlight {
      padding-top: 1rem;
      padding-bottom: 1rem;
      background-color: #5c6ac4;
      border: 1px solid #202e78;
      color: #fff;
    }
    hr {
      margin: 6rem 0;
    }
    hr+.display-3,
    hr+.display-2+.display-3 {
      margin-bottom: 2rem;
    }
  </style>
  <script type="text/javascript">
    document.documentElement.className = document.documentElement.className.replace('no-js', 'js') + (document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure", "1.1") ? ' svg' : ' no-svg');
  </script>
</head>

<body>


  <div class="container-fluid h-100 p-0">
    <div style="min-height: 100%" class="flex-row d-flex align-items-stretch m-0">
        <div class="col-lg-12 col-md-12 p-4">
            @yield("content")
        </div>
      </div>
  </div>

  <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
</body>

</html>

resources/views/layouts/global.blade.php
<!DOCTYPE html>
<!--[if IE 9]> <html class="ie9 no-js" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html class="no-js" lang="en">
<!--<![endif]-->

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>PNG @yield("title")</title>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{{asset('polished/polished.min.css')}}">
  <link rel="stylesheet" href="{{asset('polished/iconic/css/open-iconic-bootstrap.min.css')}}">
  <link rel="stylesheet" href="{{asset('vendor/font-awesome/css/font-awesome.min.css')}}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
   <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.css"/>


  <style>
    .grid-highlight {
      padding-top: 1rem;
      padding-bottom: 1rem;
      background-color: #5c6ac4;
      border: 1px solid #202e78;
      color: #fff;
    }
    hr {
      margin: 6rem 0;
    }
    hr+.display-3,
    hr+.display-2+.display-3 {
      margin-bottom: 2rem;
    }
  </style>
  <script type="text/javascript">
    document.documentElement.className = document.documentElement.className.replace('no-js', 'js') + (document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#BasicStructure", "1.1") ? ' svg' : ' no-svg');
  </script>
</head>

<body>

    <nav class="navbar navbar-expand p-0">
     <a class="navbar-brand text-center col-xs-12 col-md-3 col-lg-2 mr-0" href="/home">PiknikandGo</a>
      <button class="btn btn-link d-block d-md-none" data-toggle="collapse" data-target="#sidebar-nav" role="button" >
        <span class="oi oi-menu"></span>
      </button>
      
      <input class="border-dark bg-primary-darkest form-control d-none d-md-block w-50 ml-3 mr-2" type="text" placeholder="Search" aria-label="Search">
      <div class="dropdown d-none d-md-block">
        @if(\Auth::user())
        <button class="btn btn-link btn-link-primary dropdown-toggle" id="navbar-dropdown" data-toggle="dropdown">
          {{Auth::user()->name}}
        </button>
        @endif 
        <div class="dropdown-menu dropdown-menu-right" id="navbar-dropdown">
          <a href="{{ route('user.profile') }}" class="dropdown-item">Profile</a>
          <a href="#" class="dropdown-item">Setting</a>
          <div class="dropdown-divider"></div>
          <li>
            <form action="{{route("logout")}}" method="POST">
              @csrf
              <button class="dropdown-item" style="cursor:pointer">Sign Out</button>
            </form>
          </li>
        </div>
      </div>
    </nav>

  <div class="container-fluid h-100 p-0">
    <div style="min-height: 100%" class="flex-row d-flex align-items-stretch m-0">
        <div class="polished-sidebar bg-light col-12 col-md-3 col-lg-2 p-0 collapse d-md-inline" id="sidebar-nav">

            <ul class="polished-sidebar-menu ml-0 pt-4 p-0 d-md-block">
              <input class="border-dark form-control d-block d-md-none mb-4" type="text" placeholder="Search" aria-label="Search" />
              <li><a href="{{route('events.schedule')}}"><span class="oi oi-home"></span> Home</a></li>
              <li><a href="{{route('vacations.index')}}"><span class="fas fa-search-location"></span> Manage Vacation</a></li> 
              <li><a href="{{route('buses.index')}}"><span class="fas fa-bus-alt"></span> Manage Bus</a></li>
              <li><a href="{{ route('events') }}"><span class="oi oi-calendar"></span>Manage Schedule</a></li>
              <li><a href="{{ route('timer') }}"><span class="oi oi-clock"></span>Setting Timer</a></li>
              {{-- route('vacations.index', ['id' => $id]) --}}
              
              <div class="d-block d-md-none">
                  <div class="dropdown-divider"></div>
                  <li><a href="{{ route('user.profile',['id' => Auth::user()->id]) }}"> Profile</a></li>
                  <li><a href="#"> Setting</a></li>
                  <li>
                    <form action="{{route("logout")}}" method="POST">
                      @csrf
                      <button class="dropdown-item" style="cursor:pointer">Sign Out</button>
                    </form>
                  </li>
              </div>
            </ul>
            <div class="pl-3 d-none d-md-block position-fixed" style="bottom: 0px">
                <span class="oi oi-cog"></span> Setting
            </div>
        </div>
        <div class="col-lg-10 col-md-9 p-4">
            <div class="row ">
              <div class="col-md-12 pl-3 pt-2">
              </div>
            </div>

            @yield("content")


        </div>
      </div>
  </div>

  <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  <script src="{{asset('ckeditor/ckeditor.js')}}"></script>

    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.min.js"></script>

  @yield('footer-scripts')
</body>

</html>

resources/views/layouts/landing.blade.php
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Piknik and Go</title>

    <!-- Bootstrap core CSS -->
    <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
    

    <link rel="stylesheet" href="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/assets/owl.theme.default.min.css">
    <link rel="stylesheet" href="{{asset('vendor/font-awesome/css/font-awesome.min.css')}}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <!-- BEGIN SHAREAHOLIC CODE -->
    <link rel='preload' href='https://apps.shareaholic.com/assets/pub/shareaholic.js' as='script' />
    <script data-cfasync="false" async src="https://apps.shareaholic.com/assets/pub/shareaholic.js" data-shr-siteid="b08fd96e1072eaac42ef5d624e93b7af"></script>
    <!-- END SHAREAHOLIC CODE -->


    <!-- Custom styles for this template -->

    <link href="{{asset('css/full-slider.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('vendor/animate/animate.css')}}">
  </head>

  <body onload="initMap()">

    <!-- Navigation -->

    <nav id="headers" class="navbar navbar-expand-lg navbar-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">
          <h2>Piknik and Go</h2>
          <!-- <img src="vendor/image/brand/piknikandgo.png" alt=""> -->
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{{ route('tours') }}">Destinasi</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('bus') }}">Bus</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ route('contact') }}">Hubungi Kami</a>
            </li>
          </ul>
        </div>
        </div>
      </div>
    </nav>

    @yield("body")
  
    <!-- footer -->
    <footer id="footer">
      <div class="container">
        <div class="row">

          

              <div class="footer-menu-1 col-lg-6">
                <h1>Piknik and Go Travel</h1>
                <p>
                    Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                    Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
                </p>

                <a href="https://api.whatsapp.com/send?phone=6282130315537&text=Halo%20Admin%20Saya%20Mau%20Order%20Baju"><i class="fab fa-whatsapp"></i></a>
                <a href="https://www.instagram.com/dmctelkomuniv/" class="social-media"><i class="fab fa-instagram"></i></a> 
                <a href="#" class="social-media"><i class="fab fa-facebook-square"></i></a>
              </div>
          
          
            <div class="footer-menu-2 col-lg-6">
              <h2>Contact Information</h2>
              <div class="menu">
                  <i class="fas fa-map-marker-alt">&nbsp;Komplek Jerang Indonesia</i><br>
                  <i class="fas fa-phone-volume">&nbsp;+62 878-2095-2886</i><br>
                  <i class="far fa-envelope">&nbsp;piknikandgo@gmail.com</i>
              </div>
              
            </div>

        </div>
      </div>
    </footer>


    <!-- Bootstrap core JavaScript -->


    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js"></script>
    <script type="text/javascript" src="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/owl.carousel.js"></script>

    <script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/btn.js')}}"></script> 
    <script src="{{asset('js/dist/zoomify.js')}}"></script>
    <script src="{{asset('js/jquery.slicknav.min.js')}}"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js"></script>
    
    @yield("javascript")

  </body>
</html>